### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ghost** [vialer/vialer-js#144]
https://sentry.voipgrid.nl/sentry/voys_plugin/issues/118/

```
RangeError: Maximum call stack size exceeded
  at __mergeQueue.push (chrome-extension://ikaiemdhhhgpfdakadnlndcjjkngecmh/js/app_bg.js:1:11627)
  at h.__mergeState (chrome-extension://ikaiemdhhhgpfdakadnlndcjjkngecmh/js/app_bg.js:1:11749)
  at __mergeQueue.push (chrome-extension://ikaiemdhhhgpfdakadnlndcjjkngecmh/js/app_bg.js:1:11636)
  at h.__mergeState (chrome-extension://ikaiemdhhhgpfdakadnlndcjjkngecmh/js/app_bg.js:1:11749)
  at __mergeQueue.push (chrome-extension://ikaiemdhhhgpfdakadnlndcjjkngecmh/js/app_bg.js:1:11636)
...
(45 additional frame(s) were not displayed)
```

**Comment by ghost** [comment]
Not seen anymore after switching to faster decryption. Closing for now.
