### ISSUE TITLE
Is the right way how to install vialler-js?

### ISSUE THREAD

**Issue by welljs** [vialer/vialer-js#171]
Question 1: How to install electron version? There is no script `test_electron` in package.json
Question 2: How to install extension?

![image](https://user-images.githubusercontent.com/6547609/43194042-23fae662-900a-11e8-8955-adf9a79fd158.png)

**Comment by ghost** [comment]
Hi. Sorry for the late response. I've been a bit busy with preparing the opensource build, so the software I've moved those components to separate modules and am currently fixing the last bugs in this branch(https://github.com/vialer/vialer-js/tree/feature/restructure-module-loading). Vialer-js is normally build for Electron like:

```
# generate an unpackaged build
gulp build --brand vialer --target electron
electron build/vialer/electron/main.js
# or build an electron package; this seems broken atm
gulp build-dist --brand vialer --target electron
```

**Comment by ghost** [comment]
With the current develop branch, you should be able to run an Electron build with:
`gulp build-run --target electron`

Package a build like:
`gulp build-dist --target electron`

Hope this helps.

**Comment by ghenry** [comment]
Is there a install guide?  `gulp build-run --target electron` isn't working on Linux anyway.

Thanks.

**Comment by ghenry** [comment]
```
/home-storage/ghenry/src/vialer-js [develop*]$  gulp build-run --target electron
[10:36:28] BUILD FLAGS:
[10:36:28] - BRAND: bologna
[10:36:28] - DEPLOY: alpha
[10:36:28] - PRODUCTION: false
[10:36:28] - TARGET: electron
[10:36:28] - VERBOSE: false
[10:36:28] - LIVERELOAD: false
[10:36:28] Using gulpfile /home-storage/ghenry/src/vialer-js/gulpfile.js
[10:36:28] Starting 'build-run'...
[10:36:30] { Error: Command failed: gulp build --target electron --brand bologna;./node_modules/electron/dist/electron --js-flags='--harmony-async-await' ./build/bologna/electron/main.js
[10:36:30] 'templates' errored after 193 μs
[10:36:30] TypeError: Cannot read property 'bologna' of undefined
    at Gulp.gulp.task (/home-storage/ghenry/src/vialer-js/gulpfile.js:371:36)
    at module.exports (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home-storage/ghenry/src/vialer-js/node_modules/run-sequence/index.js:86:16)
    at runSequence (/home-storage/ghenry/src/vialer-js/node_modules/run-sequence/index.js:97:2)
    at Gulp.gulp.task (/home-storage/ghenry/src/vialer-js/gulpfile.js:80:9)
    at module.exports (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:273:3)
[10:36:30] 'scss-app' errored after 173 μs
[10:36:30] TypeError: Cannot read property 'bologna' of undefined
    at Gulp.gulp.task (/home-storage/ghenry/src/vialer-js/gulpfile.js:316:36)
    at module.exports (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home-storage/ghenry/src/vialer-js/node_modules/run-sequence/index.js:86:16)
    at runSequence (/home-storage/ghenry/src/vialer-js/node_modules/run-sequence/index.js:97:2)
    at Gulp.gulp.task (/home-storage/ghenry/src/vialer-js/gulpfile.js:307:5)
    at module.exports (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:273:3)
[10:36:30] 'scss-observer' errored after 159 μs
[10:36:30] TypeError: Cannot read property 'bologna' of undefined
    at Helpers.scssEntry (/home-storage/ghenry/src/vialer-js/tools/helpers.js:423:69)
    at Gulp.gulp.task (/home-storage/ghenry/src/vialer-js/gulpfile.js:339:20)
    at module.exports (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:214:10)
    at /home-storage/ghenry/src/vialer-js/node_modules/orchestrator/index.js:279:18
    at finish (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home-storage/ghenry/src/vialer-js/node_modules/orchestrator/lib/runTask.js:29:3)
    at runSequence (/home-storage/ghenry/src/vialer-js/gulpfile.js:309:9)
    at finish (/home-storage/ghenry/src/vialer-js/node_modules/run-sequence/index.js:60:5)
Error: unrecognized flag --harmony-async-await
Try --help for options
Error launching app
Unable to find Electron app at /home-storage/ghenry/src/vialer-js/build/bologna/electron/main.js

Cannot find module '/home-storage/ghenry/src/vialer-js/build/bologna/electron/main.js'

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'gulp build --target electron --brand bologna;./node_modules/electron/dist/electron --js-flags=\'--harmony-async-await\' ./build/bologna/electron/main.js' }

```
